### ISSUE TITLE
Add an Agents page for super users

### ISSUE THREAD

**Issue by SpinozaJoe** [markyd2/ReferralDemo#20]
Create a new Agents page only accessible by super users, which contains a table of all agents in the system with at least the following details: agent name, email address, agent type and Firm. This will allow super users to quickly access user details.

**Comment by markyd2** [comment]
Done

**Comment by SpinozaJoe** [comment]
Re-opened. Mark's change was to add admin users to a new AdminFirm called Admins. The original request was for a superuser page that shows all agents so as to make it easier to find one, rather than working out which firm they belong to first.

**Comment by SpinozaJoe** [comment]
New Agents button added to super user home page; plus menu option for Agents. An issue exists when updating or cancelling an edit to a user - you go back to the agents for that firm rather than all agents. Will raise a separate issue for this.
