### ISSUE TITLE
Add logging framework

### ISSUE THREAD

**Issue by markyd2** [markyd2/ReferralDemo#26]
All exceptions to be logged.  Visible by Admin users

**Comment by SpinozaJoe** [comment]
Now added basic Elmah functionality. Exceptions will be saved in the Referral database so you need to run Common\ThirdParty\Elmah\SQLServer.sql in the Referral DB. Custom errors are set to RemoteOnly so locally you'll still see the normal error page, and on Azure you should be redirected to the Home/Error MVC page. This can be tested by setting customerrors to On.
Currently, to see the errors go here: http://localhost/Referral/elmah.axd
I will make some more changes soon to improve this

**Comment by SpinozaJoe** [comment]
Closing now as there is now an Errors menu option for superusers which wraps around the elmah.axd resource.
