### ISSUE TITLE
Change solicitor assignment and agent visibility

### ISSUE THREAD

**Issue by markyd2** [markyd2/ReferralDemo#40]
New cases must not be assigned to a solicitor agent - they will instead default to an "unassigned" state.

Solicitor admins can use a pick list of their firm's solicitors to assign one to the case (this will appear in the workflow space).

Broker case views will name the firm and solicitor associated with the case.

Solicitor case views will name the broker associated with the case.

**Comment by SpinozaJoe** [comment]
All changes done.
